RecipeNet/urls.py
from django.contrib import admin
from django.urls import path, include
from recipe_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls"), name="accounts"),
    path('', views.index, name="index"),
    path('recipe/', include("recipe_app.urls"), name="recipeApp"),
    path('api/', include('recipe_app.urls')),
    path('upload/', views.FileUploadView.as_view(), name='file_upload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.showProfile, name='profile'),
    path('profile/edit/', views.editProfile, name="profile-edit")
]

recipe_app/urls.py
from django.urls import path, include
from . import views

app_name = "recipeApp"

urlpatterns = [
    path('new', views.create, name='create'),
    # ↓example: `/recipe/edit?id=9KqIEb6qQOk`
    path('edit', views.edit, name='edit'),
    path('setting', views.setting, name="setting"),
    path('my-recipe', views.myRecipe, name='my-recipe'),
    path('', views.findRecipe, name='index'),
    path('find-result', views.findResult, name='find-result'),
    path('show', views.showRecipe, name='show'),
    path('favorite', views.favoriteRecipe, name='favorite'),
    path('delete', views.deleteRecipe, name="delete"),
    path('deleted', views.deletedRecipe, name="deleted")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):
    account_id = models.CharField(
        verbose_name=_("account_id"),
        unique=True,
        max_length=30
    )
    account_name = models.CharField(
        verbose_name=_("account_name"),
        max_length=30
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    avatar = models.FileField(
        verbose_name=_("avatar"),
        upload_to="recipe/avatars/",
        default="defaults/avatar.png",
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id'  # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError
import mimetypes

from .models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "email",
            "birth_date",
        )


class LoginFrom(AuthenticationForm):
    class Meta:
        model = User


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "account_name",
            "avatar",
        )

    def clean_avatar(self):
        uploaded_file = self.cleaned_data['avatar']
        mime_type, encoding = mimetypes.guess_type(uploaded_file.name)
        if mime_type not in ['image/svg+xml', 'image/webp', 'image/png', 'image/jpeg', 'image/gif']:
            raise ValidationError('サポートされていないファイル形式です。')
        return uploaded_file

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.urls import reverse_lazy
from .forms import SignUpForm, LoginFrom, EditProfileForm
from .models import User
from recipe_app.models import Recipe, Favorites
from django.http import HttpResponse, HttpRequest

# Create your views here.


class SignupView(CreateView):
    """ ユーザー登録用ビュー """
    form_class = SignUpForm  # 作成した登録用フォームを設定
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("index")  # ユーザー作成後のリダイレクト先ページ

    def form_valid(self, form):
        # ユーザー作成後にそのままログイン状態にする設定
        response = super().form_valid(form)
        account_id = form.cleaned_data.get("account_id")
        password = form.cleaned_data.get("password1")
        user = authenticate(account_id=account_id, password=password)
        login(self.request, user)
        return response


class LoginView(BaseLoginView):
    form_class = LoginFrom
    template_name = "accounts/login.html"


class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("recipeApp:index")


# ==========<ここからテンプレ外>===========
def showProfile(request: HttpRequest):
    account_id: str = request.GET.get("id", None)
    user = get_object_or_404(User, account_id=account_id)
    user_recipies = Recipe.objects.filter(user=user)
    my_favorite = []
    if not request.user.is_anonymous:
        my_favorite = [c[0] for c in Favorites.objects.values_list(
            'recipe'
        ).filter(user=request.user)]
    return render(request, "accounts/profile.html", {"profile_user": user, "recipies": user_recipies, "my_favorite": my_favorite})


def editProfile(request: HttpRequest):
    form = EditProfileForm(instance=request.user)
    if request.method == "POST":
        form = EditProfileForm(
            request.POST,
            request.FILES,
            instance=request.user
        )
        if form.is_valid():
            form.save()
    return render(request, "accounts/profile_edit.html", {"form": form})

templates/accounts/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shortcut.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" />
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %} - RecipeNet</title>
</head>

<body>
    <div class="p-5">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
サインイン
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Back</a>
    </div>
</form>

<a href="{% url 'accounts:signup' %}" class="btn btn-link">
    サインアップ
</a>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
{{ profile_user.account_name }}/プロフィール
{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts/profile.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}
<div class="top">
    <img src="{{ profile_user.avatar.url }}" alt="profile-image" class="profile-img">
    <div class="names">
        <span id="account-name">{{ profile_user.account_name }}</span>
        <span id="account-id">ID: {{ profile_user.account_id }}</span>
    </div>
    <a class="edit-button" href="{% url 'accounts:profile-edit' %}">
        <img src="{% static 'images/profile/edit.svg' %}" alt="">
    </a>
</div>

<span class="middle mt-4 d-block">投稿したレシピ</span>
<div class="cards">
    {% for recipe in recipies %}
    <div class="recipe-card">
        <a href="{% url 'recipeApp:show' %}?id={{ recipe.recipe_code }}">
            <div class="recipe-img">
                <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% else %}{% static 'images/defaults/thumbnail.png' %}{% endif %}" alt="">
            </div>
            <div class="recipe-detail">
                <span class="recipe-title">{{ recipe.title }}</span>
            </div>
        </a>
        <form action="{% url 'recipeApp:favorite' %}?id={{ recipe.recipe_code }}&next={% url 'accounts:profile' %}?id={{ profile_user.account_id }}" method="post">
            {% csrf_token %}
            <button class="assesments">
                <img src="{% if recipe.id in my_favorite %}{% static 'images/recipe/favorite.svg' %}{% else %}{% static 'images/recipe/not-favorite.svg' %}{% endif %}" alt="">
                <span>{{ recipe.favorite_count }}</span>
            </button>
        </form>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends 'base.html' %}

{% block title %}
プロフィール編集
{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts/profile_edit.css' %}">
{% endblock %}

{% block content %}
{% load widget_tweaks %}
<form action="" method="post" enctype="multipart/form-data" name="mainForm">
    {% csrf_token %}
    <h1>アイコン</h1>
    <div class="avatars">
        <img src="{{ user.avatar.url }}" alt="profile-image" class="avatar" id="avatar-preview">
        <div class="edit">
            <input type="file" accept="image/*" class="file-select" name="{{ form.avatar.name }}" id="{{ form.avatar.id_for_label }}" onchange="ActivateSaveButton()">
            <img src="{% static 'images/profile/edit-white.svg' %}" alt="">
        </div>
    </div>
    <hr>
    <label for="id_account_name"><h1>表示名:</h1></label>
    <br>
    {% render_field form.account_name onkeydown="ActivateSaveButton()" %}
    <br>
    <label for="id_account_id"><h1>ID:</h1></label>
    <br>
    {% render_field form.account_id onkeydown="ActivateSaveButton()" %}
    <input type="button" value="保存済み" class="btn btn-secondary m-5 save-button" id="save" onclick="SendForm()">
</form>

{% if form.errors %}
    <ul>
        {% for field, errors in form.errors.items %}
            <li>{{ field }}:
                <ul>
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endif %}

<script>
    form = document.forms.mainForm;

    function ActivateSaveButton() {
        saveButton = document.querySelector("#save");
        saveButton.classList.replace("btn-secondary", "btn-warning");
        saveButton.value = "保存";
        window.onbeforeunload = beforeUnload;
    }

    function beforeUnload(event){
        event.preventDefault();
        event.returnValue = 'Check';
    }

    function SendForm() {
        window.onbeforeunload = null;
        form.submit()
    }

    document.getElementById('id_avatar').addEventListener('change', function(event) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('avatar-preview').src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    });
</script>
{% endblock %}

templates/accounts/signin.html
{% extends 'accounts/base.html' %}

{% block title %}
サインイン
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Back</a>
    </div>
</form>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}
サインアップ
{% endblock %}

{% block content %}
<div>
  <br>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
      <button type="submit" class="btn btn-primary">Create</button>
      <a href="{% url 'index' %}" class="btn btn-secondary">Back</a>
    </div>
  </form>
</div>

<a href="{% url 'accounts:login' %}" class="btn btn-link">
  サインイン
</a>
{% endblock %}