RecipeNet/urls.py
from django.contrib import admin
from django.urls import path, include
from recipe_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls"), name="accounts"),
    path('', views.index, name="index"),
    path('recipe/', include("recipe_app.urls"), name="recipeApp"),
    path('api/', include('recipe_app.urls')),
    path('upload/', views.FileUploadView.as_view(), name='file_upload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.showProfile, name='profile'),
    path('profile/edit/', views.editProfile, name="profile-edit")
]

recipe_app/urls.py
from django.urls import path, include
from . import views

app_name = "recipeApp"

urlpatterns = [
    path('new', views.create, name='create'),
    # ↓example: `/recipe/edit?id=9KqIEb6qQOk`
    path('edit', views.edit, name='edit'),
    path('setting', views.setting, name="setting"),
    path('my-recipe', views.myRecipe, name='my-recipe'),
    path('', views.findRecipe, name='index'),
    path('find-result', views.findResult, name='find-result'),
    path('show', views.showRecipe, name='show'),
    path('favorite', views.favoriteRecipe, name='favorite'),
    path('delete', views.deleteRecipe, name="delete"),
    path('deleted', views.deletedRecipe, name="deleted")
]

recipe_app/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


# Create your models here.

User = settings.AUTH_USER_MODEL


class PublicLevel(models.IntegerChoices):
    PRIVATE = 0, _("非公開")
    LIMITED_AND_PRIVATE = 1, _("限定公開")
    PUBLIC = 2, _("公開")


class Recipe(models.Model):
    title = models.CharField(
        verbose_name=_("title"),
        max_length=256,
    )
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        on_delete=models.SET("DELETED_USER"),
    )  # TODO: on_deleteが動くか未検証
    recipe_code = models.CharField(
        verbose_name=_("recipe_code"),
        max_length=11,
        unique=True,
    )
    recipe_image = models.ImageField(
        verbose_name=_("recipe_image"),
        upload_to="recipe/thumbnails/",
        null=True
    )
    detail = models.TextField(
        verbose_name=_("detail"),
    )
    public_level = models.IntegerField(
        verbose_name=_("public_level"),
        choices=PublicLevel,
        default=0
    )
    favorite_count = models.BigIntegerField(
        verbose_name=_("favorite_count"),
        default=0
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )
    deleted = models.BooleanField(
        verbose_name=_("deleted"),
        default=False
    )


class RecipeSection(models.Model):
    index_num = models.IntegerField(
        verbose_name=_("index_num"),
    )
    detail = models.TextField(
        verbose_name=_("detail"),
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name=_("recipe"),
        on_delete=models.CASCADE,
    )


class IngredientsSection(models.Model):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=512,
    )
    amount = models.CharField(
        verbose_name=_("amount"),
        max_length=128
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name=_("recipe"),
        on_delete=models.CASCADE,
    )
    index_num = models.IntegerField(
        verbose_name=_("index_num"),
    )


class Favorites(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        on_delete=models.SET("DELETED_USER"),
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name=_("recipe"),
        on_delete=models.CASCADE
    )

templates/recipe/create_edit.html
{% extends 'base.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/recipe/create.css' %}">
{% endblock %}

{% block title %}レシピ投稿{% endblock %}

{% block content %}
{% if thumbnail_form.errors %}
    <ul>
        {% for field, errors in thumbnail_form.errors.items %}
            <li>{{ field }}:
                <ul>
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<form action="" method="post" name="mainForm" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="d-flex">
        <!-- <h1 class="fs-1">レシピを作成</h1> -->
        <textarea name="title" id="id_title" class="title" type="text" placeholder="料理名" onkeydown="ActivateSaveButton()">{{ title }}</textarea>
        <div class="d-flex ms-auto height-min">
            <!-- <a class="my-auto me-3 setting-button p-2 rounded-circle c-pointer">  TODO: レシピの公開設定などの設定画面が表示されるようにする
                <img src="{% static 'images/recipe/settings.svg' %}" alt="settings">
            </a> -->
            <input type="button" value="保存済み" class="btn btn-secondary height-min fs-5" id="save" onclick="SendForm()">
        </div>
    </div>
    <hr>
    <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% endif %}" alt="thumbnail-image" class="thumbnail" id="thumbnail-preview">
    <input type="file" accept="image/*" class="file-select" name="{{ thumbnail_form.recipe_image.name }}" id="{{ thumbnail_form.recipe_image.id_for_label }}" onchange="ActivateSaveButton()">
    <h3>概要</h3>
    <textarea name="detail" id="id_detail" class="detail" placeholder="概要を入力...
    例: 料理の説明, 使用器具, 予想調理時間など" onkeydown="ActivateSaveButton()">{{ detail }}</textarea>
    <div class="d-flex">
        <h3>材料</h3>
        <input type="button" onclick="AddIngredientSection()" value="材料を追加" class="ms-auto btn btn-primary">
    </div>
    <ul id="ingredients" class="pt-3">
        {% for ingredient in ingredients %}
        <li>
            <div class="d-flex p-1 rounded section">
                <textarea name="ingredients_name" id="id_ingredients_name" placeholder="材料名" type="text" onkeydown="ActivateSaveButton()">{{ ingredient.0 }}</textarea>
                <textarea name="ingredients_amount" id="id_ingredients_amount" placeholder="数量" type="text" onkeydown="ActivateSaveButton()" class="ms-3">{{ ingredient.1 }}</textarea>
                <a onclick="DeleteSection(this)" class="c-pointer ms-auto p-1 rounded delete-button">
                    <img src="{% static 'images/recipe/delete.svg' %}">
                </a>
            </div>
        </li>
        {% endfor %}
    </ul>
    <hr>
    <div class="d-flex">
        <h3>手順</h3>
        <input type="button" onclick="AddSection()" value="手順を追加" class="ms-auto btn btn-primary">
    </div>
    <ol id="sections" class="pt-3">
        {% for section in sections %}
        <li>
            <div class="d-flex p-1 rounded section">
                <textarea name="section_detail" id="id_section_detail" placeholder="手順を入力..." type="text" onkeydown="ActivateSaveButton()">{{ section.0 }}</textarea>
                <a onclick="DeleteSection(this)" class="c-pointer ms-auto p-1 rounded delete-button">
                    <img src="{% static 'images/recipe/delete.svg' %}">
                </a>
            </div>
        </li>
        {% endfor %}
    </ol>
</form>


<script>
    ingredients = document.querySelector("#ingredients");
    sections = document.querySelector("#sections");
    form = document.forms.mainForm;

    function AddIngredientSection() {
        // li
        new_ingredient_li = document.createElement("li");
        // div
        new_ingredient = document.createElement("div");
        new_ingredient.className += "d-flex p-1 rounded section";
        // input1
        ingredients_name_input = document.createElement("textarea");
        ingredients_name_input.id = "id_ingredients_name";
        ingredients_name_input.name = "ingredients_name";
        ingredients_name_input.placeholder = "材料名";
        ingredients_name_input.setAttribute("type", "text");
        new_ingredient.appendChild(ingredients_name_input);
        // input2
        ingredients_amount_input = document.createElement("textarea");
        ingredients_amount_input.id = "id_ingredients_amount";
        ingredients_amount_input.name = "ingredients_amount";
        ingredients_amount_input.placeholder = "数量";
        ingredients_amount_input.setAttribute("type", "text");
        ingredients_amount_input.className += "ms-3";
        new_ingredient.appendChild(ingredients_amount_input);
        // delete button
        delete_button = document.createElement("a");
        delete_button.onclick = DeleteSection; // なぜかデバッグツールで見たら反映されないが、機能する。
        delete_button.className += "c-pointer ms-auto p-1 rounded delete-button";
        new_ingredient.appendChild(delete_button);
        // delete icon
        delete_icon = document.createElement("img");
        delete_icon.src = "{% static 'images/recipe/delete.svg' %}";
        delete_button.appendChild(delete_icon);
        // 追加
        new_ingredient_li.appendChild(new_ingredient);
        ingredients.appendChild(new_ingredient_li);
        ActivateSaveButton();
    }

    function AddSection() {
        new_section_li = document.createElement("li");

        new_section = document.createElement("div");
        new_section.className += "d-flex p-1 rounded section";

        section_input = document.createElement("textarea");
        section_input.id = "id_section_detail";
        section_input.name = "section_detail";
        section_input.placeholder = "手順を入力...";
        section_input.setAttribute("type", "text");
        new_section.appendChild(section_input);

        // delete button
        delete_button = document.createElement("a");
        delete_button.onclick = DeleteSection;
        delete_button.className += "c-pointer ms-auto p-1 rounded delete-button";
        new_section.appendChild(delete_button);
        // delete icon
        delete_icon = document.createElement("img");
        delete_icon.src = "{% static 'images/recipe/delete.svg' %}";
        delete_button.appendChild(delete_icon);

        new_section_li.appendChild(new_section)
        sections.appendChild(new_section_li);

        ActivateSaveButton()
    }

    function DeleteSection(currentElement=null) {
        try {
            currentElement.parentElement.parentElement.remove();
        }
        catch(err) {
            this.parentElement.parentElement.remove();
        }
        ActivateSaveButton();
    }

    function ActivateSaveButton() {
        saveButton = document.querySelector("#save");
        saveButton.classList.replace("btn-secondary", "btn-warning");
        saveButton.value = "保存";
        window.onbeforeunload = beforeUnload;
    }

    function beforeUnload(event){
        event.preventDefault();
        event.returnValue = 'Check';
    }

    function SendForm() {
        window.onbeforeunload = null;
        form.submit()
    }

    document.getElementById('{{ thumbnail_form.recipe_image.id_for_label }}').addEventListener('change', function(event) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('thumbnail-preview').src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    });
</script>
{% endblock %}

templates/recipe/find_recipe.html
{% extends 'base.html' %}

{% block title %}レシピを探す{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/recipe/find_recipe.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'recipeApp:find-result' %}" method="post" id="find-form">
    {% csrf_token %}
    <img src="{% static 'images/recipe/search.svg' %}" alt="">
    <input type="text" name="q" placeholder="検索..." id="query-area" onkeydown="if(event.key==='Enter'){event.preventDefault(); submitFindForm();}">
</form>

<h1 class="theme-color">人気のレシピ</h1>
<div id="top" class="cards">
    {% for recipe in top %}
    <div class="recipe-card">
        <a href="{% url 'recipeApp:show' %}?id={{ recipe.recipe_code }}">
            <div class="recipe-img">
                <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% else %}{% static 'images/defaults/thumbnail.png' %}{% endif %}" alt="">
            </div>
            <div class="recipe-detail">
                <span class="recipe-title">{{ recipe.title }}</span>
            </div>
        </a>
        <form action="{% url 'recipeApp:favorite' %}?id={{ recipe.recipe_code }}&next={% url 'recipeApp:index' %}" method="post">
            {% csrf_token %}
            <button class="assesments">
                <img src="{% if recipe.id in my_favorite %}{% static 'images/recipe/favorite.svg' %}{% else %}{% static 'images/recipe/not-favorite.svg' %}{% endif %}" alt="">
                <span>{{ recipe.favorite_count }}</span>
            </button>
        </form>
    </div>
    {% endfor %}
</div>

<!-- <h1>急上昇</h1> -->

<h1 class="theme-color">新着</h1>
<div id="new" class="cards">
    {% for recipe in new %}
    <div class="recipe-card">
        <a href="{% url 'recipeApp:show' %}?id={{ recipe.recipe_code }}">
            <div class="recipe-img">
                <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% else %}{% static 'images/defaults/thumbnail.png' %}{% endif %}" alt="">
            </div>
            <div class="recipe-detail">
                <span class="recipe-title">{{ recipe.title }}</span>
            </div>
        </a>
        <form action="{% url 'recipeApp:favorite' %}?id={{ recipe.recipe_code }}&next={% url 'recipeApp:index' %}" method="post">
            {% csrf_token %}
            <button class="assesments">
                <img src="{% if recipe.id in my_favorite %}{% static 'images/recipe/favorite.svg' %}{% else %}{% static 'images/recipe/not-favorite.svg' %}{% endif %}" alt="">
                <span>{{ recipe.favorite_count }}</span>
            </button>
        </form>
    </div>
    {% endfor %}
</div>

<!-- <h1>あなたにおすすめ</h1> -->

<script>
    function submitFindForm() {
        form = document.querySelector("#find-form");
        query = document.querySelector("#query-area").value;
        form.action = "{% url 'recipeApp:find-result' %}?q=" + query;
        form.submit();
    }
</script>
{% endblock %}

templates/recipe/find_result.html
{% extends 'base.html' %}

{% block title %}検索結果{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/recipe/find_result.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}
<form action="" method="post" id="find-form">
    {% csrf_token %}
    <img src="{% static 'images/recipe/search.svg' %}" alt="">
    <input type="text" name="q" placeholder="検索..." value="{{ query|default:'' }}" id="query-area" onkeydown="if(event.key==='Enter'){event.preventDefault(); submitFindForm();}">
</form>

{% if result %}
<div class="cards">
    {% for recipe in result %}
    <div class="recipe-card">
        <a href="{% url 'recipeApp:show' %}?id={{ recipe.recipe_code }}">
            <div class="recipe-img">
                <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% else %}{% static 'images/defaults/thumbnail.png' %}{% endif %}" alt="">
            </div>
            <div class="recipe-detail">
                <span class="recipe-title">{{ recipe.title }}</span>
            </div>
        </a>
        <form action="{% url 'recipeApp:favorite' %}?id={{ recipe.recipe_code }}&next={% url 'recipeApp:index' %}" method="post">
            {% csrf_token %}
            <button class="assesments">
                <img src="{% if recipe.id in my_favorite %}{% static 'images/recipe/favorite.svg' %}{% else %}{% static 'images/recipe/not-favorite.svg' %}{% endif %}" alt="">
                <span>{{ recipe.favorite_count }}</span>
            </button>
        </form>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="not-result">
<h3>検索結果がありません。</h3>
<div>
    <span>お花置いときますね(´・ω・)ノ</span>
    <h1>💐</h1>
</div>
{% endif %}

<script>
    function submitFindForm() {
        form = document.querySelector("#find-form");
        query = document.querySelector("#query-area").value;
        form.action = "{% url 'recipeApp:find-result' %}?q=" + query;
        form.submit();
    }
</script>
{% endblock %}

templates/recipe/my_recipe.html
{% extends 'base.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/recipe/my_recipe.css' %}">
{% endblock %}

{% block title %}マイレシピ{% endblock %}

{% block content %}
<div id="setting-overlays" class="hide">
    <div id="setting-background"></div>
    <div id="setting-window">
        <iframe src=""></iframe>
        <button id="setting-close-button" onclick="HideSetting()" tabindex="-1">
            <img src="{% static 'images/recipe/close.svg' %}" alt="close">
        </button>
        <img src="{% static 'images/recipe/loop.gif' %}" alt="" class="loading">
    </div>
</div>
<div class="titles">
    {% if not deleted %}
    <h1>マイレシピ</h1>
    <a href="{% url 'recipeApp:create' %}" class="btn btn-primary new">新規</a>
    {% else %}
    <h1>削除したレシピ</h1>
    {% endif %}
</div>
<ul>
    {% for recipe in recipies %}
    <li class="rounded">
        <a href="{% url 'recipeApp:edit' %}?id={{recipe.recipe_code}}" class="py-2 px-3" type="link">
            <div class="thumbnail">
                <img src="{% if recipe.recipe_image %}{{ recipe.recipe_image.url }}{% else %}{% static 'images/defaults/thumbnail.png' %}{% endif %}" alt="">
            </div>
            <div>
                <h2>{{ recipe.title }}</h2>
                <p class="trans">レシピコード: {{ recipe.recipe_code }}</p>
            </div>
            <div id="datetime_data" class="ms-auto d-flex flex-column">
                <p class="m-0 mt-auto trans">作成日: {{ recipe.created_at }}</p>
                <p class="m-0 trans">更新日: {{ recipe.updated_at }}</p>
            </div>
        </a>
        <a class="my-auto p-1 full-trans mx-2 rounded c-pointer more-button" onclick="ShowDropdown(this, `{{recipe.recipe_code}}`)">
            <img src="{% static 'images/recipe/more_horiz.svg' %}" alt="more" class="pe-none">
        </a>
    </li>
    {% endfor %}
</ul>
{% if not deleted %}
<a id="show-deleted" href="{% url 'recipeApp:deleted' %}">
    <img src="{% static 'images/recipe/delete.svg' %}" alt="trash">
    <span>削除したコンテンツ</span>
</a>
{% else %}
<a id="show-deleted" href="{% url 'recipeApp:my-recipe' %}">
    <span>マイレシピ</span>
</a>
{% endif %}

<div id="custom-context-menu" class="dropdown-menu pe-none" style="display: block; opacity: 0; top: 0;">
    {% if not deleted %}
    <!-- <a class="dropdown-item c-pointer" tabindex="-1">名称を変更</a> -->
    <a class="dropdown-item c-pointer" tabindex="-1" href="" id="edit-button">編集</a>
    <a class="dropdown-item c-pointer" tabindex="-1" id="copy-button">リンクをコピー</a>
    <hr class="my-1">
    <a class="dropdown-item c-pointer" tabindex="-1" id="setting-button">設定</a>
    <hr class="my-1">
    <a class="dropdown-item c-pointer text-danger" tabindex="-1" id="delete-button">削除</a>
    {% else %}
    <a class="dropdown-item c-pointer" tabindex="-1" id="delete-button">復元する</a>
    {% endif %}
</div>

<script>
    const triggerButtons = document.querySelectorAll(".more-button");
    const contextMenu = document.getElementById("custom-context-menu");

    copy_url = "";
    function ShowDropdown(currentButton, recipe_code) {
        event.preventDefault();

        redirect_url = `{% url 'recipeApp:edit' %}?id=${recipe_code}`;
        copy_url = `{% url 'recipeApp:show' %}?id=${recipe_code}`;
        delete_url  = `{% url 'recipeApp:delete' %}?id=${recipe_code}&next=` + `{% if deleted %}{% url 'recipeApp:deleted' %}{% else %}{% url 'recipeApp:my-recipe' %}{% endif %}`;

        // thisを使用してクリックされたボタンの位置を取得
        const rect = currentButton.getBoundingClientRect();
        const menuRect = contextMenu.getBoundingClientRect();
        contextMenu.style.left = `${rect.right-menuRect.width}px`;
        contextMenu.style.top = `${rect.bottom + window.scrollY}px`;

        // ボタンを有効化
        contextMenu.querySelectorAll("a").forEach(element => {
            element.setAttribute("tabindex", "");
        });
        contextMenu.className = "dropdown-menu";
        // リンクを設定
        "{% if not deleted %}"
        document.querySelector("#edit-button").href = redirect_url;
        document.querySelector("#setting-button").setAttribute("onclick", `ShowSetting('${recipe_code}')`);
        "{% endif %}"
        document.querySelector("#copy-button").onclick = CopyLink;
        document.querySelector("#delete-button").href = delete_url;
        // メニューを表示
        contextMenu.style.opacity = "1";
    }

    function HideDropdown() {
        // ボタンを無効化
        contextMenu.querySelectorAll("a").forEach(element => {
            element.setAttribute("tabindex", "-1");
        });
        contextMenu.className = "dropdown-menu pe-none";
        // メニューを非表示
        contextMenu.style.opacity = "0";
    }

    // メニュー外をクリックしたときに非表示にする
    document.addEventListener("click", function (event) {
        if (!contextMenu.contains(event.target) && !event.target.classList.contains("more-button")) {
            HideDropdown();
        }
    });

    function CopyLink() {
        navigator.clipboard.writeText(copy_url);
        HideDropdown();
    }

    setting_overlays = document.getElementById("setting-overlays");
    setting_close_button = document.getElementById("setting-close-button");
    iframe = document.querySelector("#setting-window iframe");
    function ShowSetting(recipe_code) {
        HideDropdown();
        iframe.setAttribute("src", `{% url 'recipeApp:setting' %}?id=${recipe_code}`);
        setting_overlays.className = "show";
        setting_close_button.setAttribute("tabindex", "");
    }

    function HideSetting() {
        setting_overlays.className = "hide";
        iframe.setAttribute("src", ``);
        setting_close_button.setAttribute("tabindex", "-1");
    }
</script>
{% endblock %}

templates/recipe/settings.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <title>レシピ設定 - RecipeNet</title>
</head>

{% load widget_tweaks %}
<body class="p-3 position-relative">
    <h1>設定</h1>
    <hr class="my-3">
    <form action="" method="post" id="form" name="mainForm">
        {% csrf_token %}
        <label for="id_public_level">公開設定:</label>
        <br>
        {% render_field form.public_level class+="form-select" onchange="ActivateSaveButton()" %}
        <input type="button" class="btn btn-secondary position-fixed bottom-0 end-0 m-4" id="save" value="保存済み" onclick="SendForm()">
    </form>

    <script>
        form = document.forms.mainForm;

        function ActivateSaveButton() {
            saveButton = document.querySelector("#save");
            saveButton.classList.replace("btn-secondary", "btn-warning");
            saveButton.value = "保存";
            window.onbeforeunload = beforeUnload;
        }

        function beforeUnload(event){
            event.preventDefault();
            event.returnValue = 'Check';
        }

        function SendForm() {
            window.onbeforeunload = null;
            form.submit()
        }
    </script>
</body>

</html>

templates/recipe/show_recipe.html
{% extends 'base.html' %}

{% block title %}レシピ詳細{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/recipe/show_recipe.css' %}">
{% endblock %}

{% block content %}
<div class="titles">
    <span class="title">{{ recipe.title }}</span>

    <form action="{% url 'recipeApp:favorite' %}?id={{ recipe.recipe_code }}&next={% url 'recipeApp:show' %}?id={{ recipe.recipe_code }}" method="post" id="favorite-form">
        {% csrf_token %}
        <button id="favorite-button">
            <img src="{% if is_favorite %}{% static 'images/recipe/favorite.svg' %}{% else %}{% static 'images/recipe/not-favorite.svg' %}{% endif %}" alt="" width="36px">
            <span>{{ favorite_count }}</span>
        </button>
    </form>
</div>

<h2>概要</h2>
<h3 id="recipe-detail">{{ recipe.detail|linebreaks }}</h3>

<h2>材料</h2>
<dl class="ingredients">
    {% if ingredients %}
    {% for ingredient in ingredients %}
    <button class="ingredient" onclick="changeCheck(this)">
        <div class="check" name="check">
            <img src="{% static 'images/recipe/check.svg' %}" alt="">
            <div class="line"></div>
        </div>
        <dt>{{ ingredient.name }}</dt>
        <dd>{{ ingredient.amount }}</dd>
    </button>
    {% endfor %}
    {% else %}
    このレシピには材料情報がありません(´・ω・｀)
    {% endif %}
</dl>

<h2>手順</h2>
<ol class="sections">
    {% if sections %}
    {% for section in sections %}
    <li class="section">
        <button onclick="toggleLine(this)">
            <span>{{ section.detail }}</span>
        </button>
    </li>
    {% endfor %}
    {% else %}
    このレシピには手順がありません(´・ω・｀)
    {% endif %}
</ol>

<script>
    function changeCheck(thisElement) {
        console.log("test");
        if (thisElement.classList.contains("checked")) {
            console.log("change")
            thisElement.classList.remove("checked");
        } else {
            thisElement.classList.add("checked");
        }
    }

    function toggleLine(thisElement) {
        if (thisElement.classList.contains("complete")) {
            thisElement.classList.remove("complete");
        } else {
            thisElement.classList.add("complete");
        }
    }
</script>
{% endblock %}